
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - opensearch.opster.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - opensearch.opster.io
  resources:
  - opensearchcluster
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.opster.io
  resources:
  - opensearchcluster/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.opster.io
  resources:
  - opensearchcluster/status
  verbs:
  - get
  - patch
  - update
