apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-cluster
  namespace: default
  finalizers:
    - Opster
spec:
  general:
    clusterName: my-cluster
    httpPort: 9200
    vendor: opensearch
    version: latest
    serviceName: es-svc
  dashboards:
    enable: true
  confMgmt: {}
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30
      NodeSelector:
      cpu: 4
      memory: 16
      roles:
        - "master"
        - "data"
    - component: nodes
      replicas: 3
      diskSize: 100
      NodeSelector:
      cpu: 4
      memory: 16
      roles:
        - "data"
    - component: coordinators
      replicas: 3
      diskSize: 100
      NodeSelector:
      cpu: 4
      roles:
        - "data_frozen"
        - "ingest"
