name: Testing
on: [pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - name: Test
        run: |
          echo "Starting Tests"
          cd opensearch-operator
          ls
          make test
